### ISSUE TITLE
yo fem me and shifty needs help with making a server for minecraft

### ISSUE THREAD

**Issue by darkthirsty** [greysoh/openpassy#1]
help us plz  :skull:

**Comment by darkthirsty** [comment]
bros making repos just hop on discord :( we miss you

**Comment by darkthirsty** [comment]
my guy you dead or smth come back plz 💀

**Comment by darkthirsty** [comment]
or ill spam this issue and your new repos too (jk)

**Comment by greysoh** [comment]
na
